### ISSUE TITLE
mirror article bug

### ISSUE THREAD

**Issue by script-money** [NaturalSelectionLabs/Cheers#160] opened 2021-12-23 01:55 UTC
**Describe the bug**
One of my articles may have been edited, but the duplicate appears at https://scriptmoney.rss3.bio/

**Expected behavior**
Not duplicate content

**Screenshots**
<img width="488" alt="Screen Shot 2021-12-23 at 9 52 50 AM" src="https://user-images.githubusercontent.com/74860630/147175580-5d6d89cc-4185-4b8b-9508-eeb3ad65d43c.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Brave
 - Version 1.33.106

**Additional context**
Another bug: The article is in markdown format, but is not rendered correctly on bio

**Comment by Candinya** [comment] 2021-12-26 15:48
This is not a bug, since we grab mirror articles directly from arweave, old versions just keeps there (so as some deleted articles).
But we can try to enhance this by filter out the duplicate articles by title.
Thanks for your report. Will be fixed soon.

**Closed** 2022-02-08 06:23 UTC
Labels: enhancement
